# Generated by Django 2.2.4 on 2020-01-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0002_remove_studentprofilepicture_picture_url_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultylistlor',
            name='comments',
            field=models.CharField(blank=True, max_length=750),
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='strengths',
            field=models.CharField(blank=True, max_length=750),
        ),
    ]
